package com.and_backend.enums;

public enum LossReason { PARTNER_LOST_FEELINGS, I_LOST_FEELINGS, PERSONALITY_GAP, BETRAYAL, SITUATIONAL, UNSURE_LOVER,
    NATURAL_DEATH, ILLNESS_ACCIDENT, EUTHANASIA, MISSING, UNSURE_PET,
    FIGHT, SUDDEN_CUTOFF, NATURSAL_DRIFT, HURTED_BY_FRIEND, COMPLICATED, UNSURE_FRIEND,
    DEATH_NATURAL, DEATH_ACCIDENT, CUT_OFF, DIVORCE, LONG_TERM_DISTANCE, UNSURE_FAMILY
}
